# Numpy

In [1]:
ages = [1,2,3,4,5,6,7,8,9]
mean = sum(ages) / len(ages)
print(mean)

5.0


In [2]:
import numpy as np

ages = np.array(ages)
print(ages)
print(ages.max())
print(ages.min())
print(ages.mean())

[1 2 3 4 5 6 7 8 9]
9
1
5.0


In [3]:
np.average(ages)

5.0

In [4]:
np.std(ages)

2.581988897471611

In [5]:
a1d = np.array([1,2,3,4,5,6,7,8,9])

In [6]:
a2d = np.array([[1,2], [3,4], [5,6]])

In [7]:
a3d = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[1,3,5], [2,4,6], [7,8,9]], [[1,5,9], [2,4,6], [6,8,3]]])

In [8]:
print(a3d.dtype)

int64


In [9]:
a3d = a3d.astype(np.uint64)
print(a3d.dtype)

uint64


In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,12, 3, dtype = float)

array([ 1.,  4.,  7., 10.])

In [12]:
np.linspace(10, 12)

array([10.        , 10.04081633, 10.08163265, 10.12244898, 10.16326531,
       10.20408163, 10.24489796, 10.28571429, 10.32653061, 10.36734694,
       10.40816327, 10.44897959, 10.48979592, 10.53061224, 10.57142857,
       10.6122449 , 10.65306122, 10.69387755, 10.73469388, 10.7755102 ,
       10.81632653, 10.85714286, 10.89795918, 10.93877551, 10.97959184,
       11.02040816, 11.06122449, 11.10204082, 11.14285714, 11.18367347,
       11.2244898 , 11.26530612, 11.30612245, 11.34693878, 11.3877551 ,
       11.42857143, 11.46938776, 11.51020408, 11.55102041, 11.59183673,
       11.63265306, 11.67346939, 11.71428571, 11.75510204, 11.79591837,
       11.83673469, 11.87755102, 11.91836735, 11.95918367, 12.        ])

# Calculating Standard Deviation

In [13]:
import numpy as np
ages = [1,2,3,4,5,6,7,8,9]
ages = np.array(ages)
mean = ages.mean()

In [14]:
dists = ages - mean
print(dists)

[-4. -3. -2. -1.  0.  1.  2.  3.  4.]


In [15]:
dists = dists*dists
dists

array([16.,  9.,  4.,  1.,  0.,  1.,  4.,  9., 16.])

In [16]:
summed_dists = np.sum(dists)
summed_dists

60.0

In [17]:
avg_dist = summed_dists / (len(ages)-1)
avg_dist

7.5

In [18]:
std_dev = np.sqrt(avg_dist)
ages, std_dev

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), 2.7386127875258306)

## Benefit of using Numpy

In [19]:
std_devn = np.std(ages)
std_devn

2.581988897471611